### ISSUE TITLE
improve the rspec test against: run this automatically

### ISSUE THREAD

**Issue by MalloZup** [openSUSE/gitarro#10]
- [x] improved testing with acceptance tests

- [x] use rspec for acceptance tests

- [x] create how to contriubte small doc

- [x] Increase coverage if needed (analyze it)

- [x] find a way to mock github prs https://github.com/octokit/fixtures#how-it-works

**Comment by MalloZup** [comment]
- [ ] improved testing with acceptance tests

- [ ] use rspec for acceptance tests

- [ ] create how to contriubte small doc

**Comment by MalloZup** [comment]
closing, at moment rspec is doing good work with locally forked repos
